version: 1
project:
  license: CC-BY-4.0
  open_access: true
  venue: Nucleus
  subject: Developer Note
  github: https://github.com/bnext-bio/nucleus-developer-notes
  references:
    devnotes: https://devnotes.bnext.bio
  jupyter: true
  exports:
    - format: meca
      id: meca
    - format: typst
      template: https://github.com/curvenote-templates/bnext.git
      article: main.md
      output: devnote.pdf
      id: article
  resources:
    - figures/**/*
    - general/**/*
    - General/**/*
    - experiments/**/*
    - Experiments/**/*
    - resources/**/*
    - Resources/**/*
    - plasmids/**/*
    - Plasmids/**/*
  downloads:
    - id: article
      title: Download Article PDF
    - id: meca
      title: Computational Archive
      filename: calpoly-2026-chem471-devnote04-archive.zip
site:
  template: article-theme
  nav: []
